# Generated by Django 3.2.6 on 2021-10-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_hero_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='score',
        ),
    ]
